---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: argo-service
  replicas: 1
  template:
    metadata:
      labels:
        run: argo-service
    spec:
      containers:
      - name: argo-service
        image: agrimmer/argo-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: argo-service
  namespace: keptn
  labels:
    run: argo-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: argo-service
---
## argo-service sh.keptn.event.configuration.change
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-service-evaluation-done-distributor
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: distributor
  replicas: 1
  template:
    metadata:
      labels:
        run: distributor
    spec:
      containers:
        - name: distributor
          image: keptn/distributor:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.events.evaluation-done'
            - name: PUBSUB_RECIPIENT
              value: 'argo-service'
