---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-argo-service
  labels:
    "app": "keptn"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-argo-service-rollouts
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - "argoproj.io"
    resources:
      - rollouts
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-argo-service-rollouts
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-argo-service-rollouts
subjects:
  - kind: ServiceAccount
    name: keptn-argo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-service
spec:
  selector:
    matchLabels:
      run: argo-service
  replicas: 1
  template:
    metadata:
      labels:
        run: argo-service
    spec:
      serviceAccountName: keptn-argo-service
      containers:
        - name: argo-service
          image: keptncontrib/argo-service:0.1.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: distributor
          image: keptn/distributor:0.7.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.events.evaluation-done'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: argo-service
  labels:
    run: argo-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: argo-service
