---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-argo-service
  namespace: keptn  
  labels:
    "app": "keptn"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-argo-service-rollouts
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - "argoproj.io"
    resources:
      - rollouts
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-argo-service-rollouts
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
#  name: cluster-admin
  name: keptn-argo-service-rollouts
subjects:
  - kind: ServiceAccount
    name: keptn-argo-service
    namespace: keptn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-service
  namespace: keptn  
  labels:
    app.kubernetes.io/name: argo-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: execution-plane   
spec:
  selector:
    matchLabels:
      run: argo-service
  replicas: 1
  template:
    metadata:
      labels:
        run: argo-service
    spec:
      serviceAccountName: keptn-argo-service
      containers:
        - name: argo-service
          image: grabnerandi/argo-service:0.8.0 # set to released version
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: distributor
          image: keptn/distributor:0.8.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.release.triggered,sh.keptn.event.rollback.triggered,sh.keptn.event.test.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
apiVersion: v1
kind: Service
metadata:
  name: argo-service
  namespace: keptn  
  labels:
    run: argo-service
    app.kubernetes.io/name: argo-service
    app.kubernetes.io/instance: keptn
    app.kubernetes.io/part-of: keptn-keptn
    app.kubernetes.io/component: execution-plane    
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: argo-service
